### PR TITLE
Temopral Reasoning 

### PR DESCRIPTION
**Pull request by tanksha**
This PR Includes
- Rules required for temporal deduction
- Look back variant temporal reasoning
- Unit tests

### CODE REVIEW

**Comment by tanksha** [comment]
@ngeiswei I have compiled the recent works in these PR, please review them when you have time. Thanks

**Comment by ngeiswei** [comment]
Thanks @tanksha ! Very minor first remark: `PLNRulesIntegrationTest` should be renamed `PLNRulesIntegrationUTest`.

**Comment by ngeiswei** [comment]
Oh, apologies, you didn't write `PLNRulesIntegrationTest`!

**Comment by ngeiswei** [comment]
Also, it is generally better if you create a new branch as opposed to using master.  It makes it easier to organize your work and clearer for others as well.

**Comment by ngeiswei** [comment]
Also, when possible, before creating the PR, it's better to rebase your branch onto the upstream/master, as opposed to say merge the upstream/master into your branch after creating the PR, that way your commits appear at the top of the git history, which is slightly easier to review.

**Comment by ngeiswei** [comment]
CircleCI fails due to not having pln being installed before running the unit tests.  Joel Pitt developed a way to avoid.  I recall having being able to use it but I also recall that it's tricky.  So you should either fix pln so that it doesn't need to be installed to run its unit tests, or you should fix circleci to install pln before running the unit tests.

For fixing circleci you have a look at asmoses, which does install asmoses before running its unit tests.  And for fixing pln you can have a look at the atomspace repo.  Maybe we can look into that during the call.

**Comment by ngeiswei** [comment]
@tanksha, since `TemporalReasoningUTest` is only testing rules individually I think it would be more appropriate to have it under the `rules` subfolder alongside `PLNRulesUTest.cxxtest`, and to rename it to `TemporalReasoningRulesUTest`.

**Comment by ngeiswei** [comment]
BTW, when you'll make integrated unit tests you'll have to use the PLN's API from the `pln` guile module.  I'm gonna fix `PLNRulesIntegrationTest` to use the `pln` module which should give you an example.  I'll try to fix the need for installing pln to run the utests as well, but I don't promise anything, as I said it's tricky.

**Pull request closed without merging**
